// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// arma_dist_al
arma::mat arma_dist_al(const arma::mat& X);
RcppExport SEXP _spbalDAS_arma_dist_al(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_dist_al(X));
    return rcpp_result_gen;
END_RCPP
}
// hungarian_arma
List hungarian_arma(const arma::mat cost);
RcppExport SEXP _spbalDAS_hungarian_arma(SEXP costSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type cost(costSEXP);
    rcpp_result_gen = Rcpp::wrap(hungarian_arma(cost));
    return rcpp_result_gen;
END_RCPP
}
// DAS_cpp
IntegerMatrix DAS_cpp(const NumericMatrix& pop_, int n, bool verbose);
RcppExport SEXP _spbalDAS_DAS_cpp(SEXP pop_SEXP, SEXP nSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type pop_(pop_SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(DAS_cpp(pop_, n, verbose));
    return rcpp_result_gen;
END_RCPP
}
// arma_setdiff
arma::uvec arma_setdiff(arma::uvec x, arma::uvec y);
RcppExport SEXP _spbalDAS_arma_setdiff(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(arma_setdiff(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spbalDAS_arma_dist_al", (DL_FUNC) &_spbalDAS_arma_dist_al, 1},
    {"_spbalDAS_hungarian_arma", (DL_FUNC) &_spbalDAS_hungarian_arma, 1},
    {"_spbalDAS_DAS_cpp", (DL_FUNC) &_spbalDAS_DAS_cpp, 3},
    {"_spbalDAS_arma_setdiff", (DL_FUNC) &_spbalDAS_arma_setdiff, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_spbalDAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
