// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// native_lapjv
Rcpp::List native_lapjv(Rcpp::NumericMatrix Cost_R);
RcppExport SEXP _spbalDAS_native_lapjv(SEXP Cost_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Cost_R(Cost_RSEXP);
    rcpp_result_gen = Rcpp::wrap(native_lapjv(Cost_R));
    return rcpp_result_gen;
END_RCPP
}
// LinearAssignmentProblem_cpp
Rcpp::IntegerMatrix LinearAssignmentProblem_cpp(const arma::mat& pop, arma::uword target_n, arma::uword initial_J, int n_threads, bool verbose, bool cache_W);
RcppExport SEXP _spbalDAS_LinearAssignmentProblem_cpp(SEXP popSEXP, SEXP target_nSEXP, SEXP initial_JSEXP, SEXP n_threadsSEXP, SEXP verboseSEXP, SEXP cache_WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type pop(popSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type target_n(target_nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type initial_J(initial_JSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type cache_W(cache_WSEXP);
    rcpp_result_gen = Rcpp::wrap(LinearAssignmentProblem_cpp(pop, target_n, initial_J, n_threads, verbose, cache_W));
    return rcpp_result_gen;
END_RCPP
}
// arma_dist_al
arma::mat arma_dist_al(const arma::mat& X);
RcppExport SEXP _spbalDAS_arma_dist_al(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_dist_al(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spbalDAS_native_lapjv", (DL_FUNC) &_spbalDAS_native_lapjv, 1},
    {"_spbalDAS_LinearAssignmentProblem_cpp", (DL_FUNC) &_spbalDAS_LinearAssignmentProblem_cpp, 6},
    {"_spbalDAS_arma_dist_al", (DL_FUNC) &_spbalDAS_arma_dist_al, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_spbalDAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
