# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name hungarian_solve
#'
#' @title Wrapper that calls native_lapjv.
#'
#' @description ...
#'
#' @author Phil Davies.
#'
#' @param cost The cost matrix.
#' @param Assignment The assignment vector.
#'
#' @return The total cost.
#'
NULL

#' @name native_lapjv
#'
#' @title Solve the Linear Assignment Problem.
#'
#' @description Solves the linear assignment problem using the Jonker-Volgenant algorithm.
#'
#' @author Phil Davies.
#'
#' @param Cost_R The cost matrix.
#'
#' @return A list containing two variables, cost and assignment.
#'
#' @examples
#' # Cost matrix for three 3D points. $cost = 1, $assignment = 2, 1, 0
#' spbalDAS::native_lapjv(Cost_R = rbind(c(1, 2, 0), c(2, 0, 1), c(1, 4, 19)))
#' # Cost matrix for three 3D points. $cost = 10, $assignment = 1, 0, 2
#' spbalDAS::native_lapjv(Cost_R = rbind(c(4, 2, 8), c(2, 3, 7), c(3, 1, 6)))
#' # Assign 4 machines to 4 jobs to minimize total setup time. $cost = 15, $assignment = 1, 3, 2, 0
#' spbalDAS::native_lapjv(Cost_R = rbind(c(14, 5, 8, 7), c(2, 12, 6, 5), c(7, 8, 3, 9), c(2, 4, 6, 10)))
#' # $cost = 55, $assignment = 2, 3, 4, 0, 1
#' spbalDAS::native_lapjv(Cost_R = rbind(c(10, 4, 6, 10, 12), c(11, 7, 7, 9, 14), c(13, 8, 12, 14, 15), c(14, 16, 13, 17, 17), c(17, 11, 17, 20, 19)))
#'
#' @export
native_lapjv <- function(Cost_R) {
    .Call(`_spbalDAS_native_lapjv`, Cost_R)
}

#' @name LinearAssignmentProblem_cpp
#'
#' @title Solve the Linear Assignment Problem.
#'
#' @description Solves the linear assignment problem using the hungarian algorithm.
#'
#' @author Phil Davies.
#'
#' @param W_R A weight matrix.
#' @param target_n The number of sample points required.
#' @param N The number of points in the population.
#' @param initial_J ...
#' @param n_threads The maximum number of threads to use. Default value is 1.
#' @param verbose When set true will display debug and informational messages.
#'
#' @return The sample matrix.
#'
#' @examples
#' # Distance matrix for the two 3D points.
#' spbalDAS::arma_dist_al(X = rbind(c(1, 2, 3), c(4, 3, 2)))
#' # Distance matrix for three 2D points.
#' spbalDAS::arma_dist_al(X = matrix(c(2, 3, 0, 9, 4, 5), nrow = 3, byrow = TRUE))
#'
#' @export
LinearAssignmentProblem_cpp <- function(W_R, target_n, N, initial_J, n_threads = 1L, verbose = FALSE) {
    .Call(`_spbalDAS_LinearAssignmentProblem_cpp`, W_R, target_n, N, initial_J, n_threads, verbose)
}

#' @name arma_dist_al
#'
#' @title Calculate a distance matrix.
#'
#' @description Computes a distance matrix for the supplied matrix of n-dimensional points
#'              using Euclidean distance.
#'
#' @author Phil Davies.
#'
#' @param X An n-dimensional matrix of points.
#'
#' @return The distance matrix for the point matrix X.
#'
#' @examples
#' # Distance matrix for the two 3D points.
#' spbalDAS::arma_dist_al(X = rbind(c(1, 2, 3), c(4, 3, 2)))
#' # Distance matrix for three 2D points.
#' spbalDAS::arma_dist_al(X = matrix(c(2, 3, 0, 9, 4, 5), nrow = 3, byrow = TRUE))
#'
#' @export
arma_dist_al <- function(X) {
    .Call(`_spbalDAS_arma_dist_al`, X)
}

